### PR TITLE
Merge 0.12.x branch to 0.14.x

### PR DESCRIPTION
**Pull request by thenonameguy**
Accidentally opened this PR to the wrong branch. Would it be possible to release a patch version after this gets merged for 0.14.x?

### CODE REVIEW

**Comment by thenonameguy** [comment]
@lbradstreet  ping please? :) This has been already accepted, just to the wrong branch.
https://github.com/onyx-platform/onyx-spec/pull/4

**Comment by thenonameguy** [comment]
I would glady take this project over to make it feature-complete with plumatic/schema.

**Comment by lbradstreet** [comment]
Sorry that I didn't see this. I had already half fixed this by cherry picking the commit to master. Everything releases off of master, so I just ran our release script to cut a release which will tag and merge the changes into 0.14.x. You should see a release ship to clojars as soon as CI runs.

**Comment by thenonameguy** [comment]
Thank you! Closing.

**Pull request closed without merging**
